# Generated by Django 3.2 on 2022-04-13 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('second_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('third_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('fourth_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('fourth_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('fifth_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('fifth_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
