# Generated by Django 3.2 on 2022-04-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_rating',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
